steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      ["-c", "docker pull gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest || exit 0"]
    env:
      - DOCKER_BUILDKIT=1
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest"
      - "-t"
      - "gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA"
      - "-t"
      - "gcr.io/$PROJECT_ID/${_IMAGE_NAME}:${_SANITIZED_BRANCH_NAME}-latest"
      - "--cache-from"
      - "gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest"
      - "--cache-from"
      - "gcr.io/$PROJECT_ID/${_IMAGE_NAME}:${_SANITIZED_BRANCH_NAME}-latest"
      - "-f"
      - "Dockerfile"
      - "--build-arg"
      - "NPM_AUTH_TOKEN=$$NPM_AUTH_TOKEN"
      - "."
    env:
      - DOCKER_BUILDKIT=1
  - name: gcr.io/cloud-builders/docker
    args:
      - "-c"
      - |
        docker push gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest
        docker push gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA
        docker push gcr.io/$PROJECT_ID/${_IMAGE_NAME}:${_SANITIZED_BRANCH_NAME}-latest
    entrypoint: bash
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "services"
      - "update"
      - "dev-${_IMAGE_NAME}"
      - "--region=asia-southeast1"
      - "--update-env-vars=COMMIT_SHA=$COMMIT_SHA"
timeout: 1000s
options:
  dynamicSubstitutions: true
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _IMAGE_NAME: deflora-spa-service
  _SANITIZED_BRANCH_NAME: '${BRANCH_NAME//\//-}'
