steps:
  - name: gcr.io/cloud-builders/docker
    env:
      - DOCKER_BUILDKIT=1
    args:
      - "-c"
      - "docker pull gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$TAG_NAME || exit 0"
    entrypoint: bash
  - name: gcr.io/cloud-builders/docker
    env:
      - DOCKER_BUILDKIT=1
    args:
      - build
      - "-t"
      - "gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$TAG_NAME"
      - "--cache-from"
      - "gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$TAG_NAME"
      - "-f"
      - Dockerfile
timeout: 1000s
images:
  - "gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$TAG_NAME"
options:
  dynamicSubstitutions: true
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _IMAGE_NAME: deflora-spa-service
